<?php/*Ukrainian Language FilesetProduced by kot2007E-mail: koot2007@gmail.comv.9.00.00 beta*/
// Locale Settingssetlocale(LC_TIME, 'uk_UA.utf8'); // Linux Server (Windows may differ)$locale['charset'] = "utf-8";$locale['xml_lang'] = "ua";$locale['tinymce'] = "en";$locale['phpmailer'] = "ua";
// Full & Short Months$locale['months'] = "&nbsp;|Січень|Лютий|Березень|Квітень|Травень|Червень|Липень|Серпень|Вересень|Жовтень|Листопад|Грудень";$locale['shortmonths'] = "&nbsp|Січ|Лют|Бер|Кві|Тра|Чер|Лип|Сер|Вер|Жов|Лис|Гру";// Timers$locale['year'] = "рік";$locale['year_a'] = "роки(ів)";$locale['month'] = "місяць";$locale['month_a'] = "місяці(в)";$locale['day'] = "день";$locale['day_a'] = "дні(в)";$locale['hour'] = "година";$locale['hour_a'] = "годин(и)";$locale['minute'] = "хвилина";$locale['minute_a'] = "хвилин(и)";$locale['second'] = "секунда";$locale['second_a'] = "секунд(и)";$locale['just_now'] = "щойно";$locale['ago'] = "тому";// Geo$locale['street1'] = "Адреса 1";$locale['street2'] = "Адреса 2";$locale['city'] = "Місто";$locale['postcode'] = "Поштовий індекс";$locale['sel_country'] = "Вибір країни";$locale['sel_state'] = "Вибір регіону";
// Standard User Levels$locale['user0'] = "Загальний";$locale['user1'] = "Користувач";$locale['user2'] = "Адміністратор";$locale['user3'] = "Супер адміністратор";$locale['user_na'] = "не визначено";$locale['user_anonymous'] = "Анонім";
// Standard User Status$locale['status0'] = "Активний";$locale['status1'] = "Заблокований";$locale['status2'] = "Неактивований";$locale['status3'] = "Призупинений";$locale['status4'] = "Заблокований з міркувань безпеки";$locale['status5'] = "Скасований";$locale['status6'] = "Анонімний";$locale['status7'] = "Деактивований";$locale['status8'] = "Неактивний";
// Forum Moderator Level(s)$locale['userf1'] = "Модератор";
// Navigation$locale['global_001'] = "Навігація";$locale['global_002'] = "Посилання відсутні\n";
// Users Online$locale['global_010'] = "Зараз на сайті";$locale['global_011'] = "Гостей";$locale['global_012'] = "Користувачів";$locale['global_013'] = "Користувачі відсутні";$locale['global_014'] = "Всього користувачів";$locale['global_015'] = "Неактивних користувачів";$locale['global_016'] = "Новий користувач";
// Forum Side panel$locale['global_020'] = "Теми форуму";$locale['global_021'] = "Нові теми";$locale['global_022'] = "Обговорювані";$locale['global_023'] = "Теми відсутні";
// Comments Side panel$locale['global_025'] = "Останні коментарі";$locale['global_026'] = "Коментарі відсутні";
// Articles Side panel$locale['global_030'] = "Останні статті";$locale['global_031'] = "Статті відсутні";
// Downloads Side panel$locale['global_032'] = "Останні завантаження";$locale['global_033'] = "Завантаження відсутні";
// Welcome panel$locale['global_035'] = "Ласкаво просимо";
// Latest Active Forum Threads panel$locale['global_040'] = "Останні активні теми на форумі";$locale['global_041'] = "Мої теми";$locale['global_042'] = "Мої повідомлення";$locale['global_043'] = "Нові повідомлення";$locale['global_044'] = "Теми";$locale['global_045'] = "Переглядів";$locale['global_046'] = "Відповідей";$locale['global_047'] = "Останні повідомлення";$locale['global_048'] = "Форум";$locale['global_049'] = "Додано";$locale['global_050'] = "Автор";$locale['global_051'] = "Опитування";$locale['global_052'] = "Переміщено";$locale['global_053'] = "Ви не створювали тем на форумі";$locale['global_054'] = "Ви не залишали повідомлень на форумі";$locale['global_055'] = "З часу Вашого останнього візиту є %u нове(их) повідомлення(нь) в %u темі(ах).";$locale['global_056'] = "Мої підписки на теми";$locale['global_057'] = "Параметри";$locale['global_058'] = "Відміна";$locale['global_059'] = "Ви не підписані на жодну тему";$locale['global_060'] = "Скасувати підписку на цю тему?";
// News & Articles$locale['global_070'] = "Опубліковано: ";$locale['global_071'] = " ";$locale['global_072'] = "Читати далі...";$locale['global_073'] = " коментарів";$locale['global_073b'] = " коментар";$locale['global_074'] = " переглядів";$locale['global_075'] = "Друк";$locale['global_076'] = "Редагувати";$locale['global_077'] = "Новини";$locale['global_078'] = "Новини відсутні";$locale['global_079'] = "Категорія: ";$locale['global_080'] = "Несортовані";
// Page Navigation$locale['global_090'] = "&laquo;Попередня";$locale['global_091'] = "Наступна&raquo;";$locale['global_092'] = "Сторінка ";$locale['global_093'] = " з ";
// Guest User Menu$locale['global_100'] = "Авторизація";$locale['global_101'] = "Ім'я";$locale['global_102'] = "Пароль";$locale['global_103'] = "входити автоматично";$locale['global_104'] = "Вхід&nbsp;&raquo;";$locale['global_105'] = "Ще не зареєстровані? <a href='".BASEDIR."register.php' class='side'>Зареєструватися</a>";$locale['global_106'] = "Не пам`ятаєте пароль? <br /><a href='".BASEDIR."lostpassword.php' class='side'>Відновити</a>";$locale['global_107'] = "Реєстрація на сайті";$locale['global_108'] = "Відновлення паролю";
// User Menu$locale['global_123'] = "Центр керування";$locale['UM060'] = "Авторизація";$locale['UM061'] = "Ім'я";$locale['UM061a'] = "Адреса E-mail";$locale['UM061b'] = "Ім'я або адреса E-mail";$locale['UM062'] = "Пароль";$locale['UM063'] = "Запам'ятати мене";$locale['UM064'] = "Авторизація";$locale['UM065'] = "Ще не зареєстровані?<br /><a href='".BASEDIR."register.php' class='side'>Зареєструватися</a>.";$locale['UM066'] = "Не пам'ятаєте пароль?<br /><a href='".BASEDIR."lostpassword.php' class='side'>Відновити</a>.";$locale['UM080'] = "Профіль";$locale['UM081'] = "Приватні повідомлення";$locale['UM082'] = "Користувачі";$locale['UM083'] = "Центр керування";$locale['UM084'] = "Вихід";$locale['UM085'] = "У Вас %u ";$locale['UM086'] = "повідомлення";$locale['UM087'] = "повідомлень";$locale['UM088'] = "Відстежувані теми";// Submit (news, link, article)$locale['UM089'] = "Надіслати...";$locale['UM090'] = "Додати новину";$locale['UM091'] = "Додати посилання";$locale['UM092'] = "Додати статтю";$locale['UM093'] = "Додати фото";$locale['UM094'] = "Додати завантаження";// User Panel$locale['UM095'] = "Вітаємо: ";$locale['UM096'] = "Особисте меню";$locale['UM097'] = "Зміна мови";// Gauges$locale['UM098'] = "Вхідні:";$locale['UM099'] = "Вихідні:";$locale['UM100'] = "Архів:";
// Poll$locale['global_130'] = "Опитування";$locale['global_131'] = "Голосувати";$locale['global_132'] = "Для участі в опитуваннях Ви повинні авторизуватися";$locale['global_133'] = "голос";$locale['global_134'] = "голосів";$locale['global_135'] = "Всього голосів: ";$locale['global_136'] = "Розпочато: ";$locale['global_137'] = "Завершено: ";$locale['global_138'] = "Архів опитувань";$locale['global_139'] = "Виберіть опитування зі списку:";$locale['global_140'] = "Перегляд";$locale['global_141'] = "Перегляд опитування";$locale['global_142'] = "Опитування відсутні.";
// Captcha$locale['global_150'] = "Код підтвердження:";$locale['global_151'] = "Введіть код підтвердження:";
// Footer Counter$locale['global_170'] = "відвідувач";$locale['global_171'] = "відвідувачів";$locale['global_172'] = "Завантажено за %s сек.";$locale['global_173'] = "Запити";
// Admin Navigation$locale['global_180'] = "Центр керування";$locale['global_181'] = "Повернутися на сайт";$locale['global_182'] = "<strong>Зауваження:</strong> Пароль адміністрування введено некоректно";
// Miscellaneous$locale['global_190'] = "Ввімкнено режим обслуговування";$locale['global_191'] = "Вашу IP адресу заблоковано";$locale['global_192'] = "Термін Вашої сесії закінчився. Будь ласка, авторизуйтесь знову, щоб продовжити.";$locale['global_193'] = "Не вдалося встановити файл cookie. Будь ласка, переконайтеся, що у переглядачі ввімкнено дозвіл на встановлення файлів cookie , щоб мати можливість увійти належним чином.";$locale['global_194'] = "Дію цього облікового запису на даний час призупинено";$locale['global_195'] = "Цей обліковий запис ще не активовано";$locale['global_196'] = "Вказані ім`я та\або пароль некоректні";$locale['global_197'] = "Будь ласка, зачекайте ...<br />Відбувається перевірка авторизації Вашого облікового запису.<br /><br />[ <u><b><a href='index.php'>можете натиснути тут, якщо не бажаєте більше чекати</a></b></u> ]";$locale['global_198'] = "<strong>Увага:</strong> Знайдено файл setup.php, будь ласка, видаліть його негайно!";$locale['global_199'] = "<strong>Увага:</strong> Не введено пароль адміністрування, натисніть <u><b><a href='".BASEDIR."edit_profile.php'>Редагувати обліковий запис</a></b></u> і введіть його";
//Titles$locale['global_200'] = " - ";$locale['global_201'] = ": ";$locale['global_202'] = $locale['global_200']."Пошук";$locale['global_203'] = $locale['global_200']."ЧАП";$locale['global_204'] = $locale['global_200']."Форум";
//Themes$locale['global_210'] = "Перейти до змісту";
// No themes found$locale['global_300'] = "Тему сайту не визначено";$locale['global_301'] = "Вибачте, неможливо відобразити сторінку. Через певні обставини, неможливо знайти жодну тему сайту. Якщо Ви адміністратор сайту, використайте менеджер FTP для завантаження теми оформлення, яка сумісна з <em>PHP-Fusion v7</em> в каталог <em>themes/</em>. Після завантаження теми, перевірте у розділі <em>Налаштування - Головне</em> Центру керування, що завантажена тема в каталог <em>themes/</em> активована. Майте на увазі, що завантажена тема повинна мати ту ж назву (враховуючи регістр символів; важливо для Unix-серверів), що й вибрана тема в розділі <em>Налаштування - Головне</em> Центру керування.<br /><br />Якщо Ви користувач, будь ласка, зв'яжіться з адміністратором сайту за адресою Е-mail: ".hide_email($settings['siteemail'])." та повідомте про цю проблему.";$locale['global_302'] = "Вибрана тема в розділі <em>Налаштування - Головне</em>, відсутня або пошкоджена!";// JavaScript Not Enabled$locale['global_303'] = "Ой, сталась помилка! А де ж <strong>JavaScript</strong>?<br />Схоже, що Ваш веб браузер не підтримує технологію JavaScript, або її наразі вимкнено. Будь ласка, <strong>увімкніть JavaScript</strong> для коректного відображення цього вебсайту,<br /> або <strong>використайте для перегляду інший веб браузер</strong>, який має підтримку JavaScript; <a href='http://firefox.com' rel='nofollow' title='Mozilla Firefox'>Firefox</a>, <a href='http://apple.com/safari/' rel='nofollow' title='Safari'>Safari</a>, <a href='http://opera.com' rel='nofollow' title='Opera Web Browser'>Opera</a>, <a href='http://www.google.com/chrome' rel='nofollow' title='Google Chrome'>Chrome</a> або версію <a href='http://www.microsoft.com/windows/internet-explorer/' rel='nofollow' title='Internet Explorer'>Internet Explorer</a> не нижче 7.";
// User Management
// Member status$locale['global_400'] = "призупинено";$locale['global_401'] = "заблоковано (бан)";$locale['global_402'] = "деактивовано";$locale['global_403'] = "обліковий запис знищено";$locale['global_404'] = "обліковий запис анонімний";$locale['global_405'] = "анонімний користувач";$locale['global_406'] = "Цей обліковий запис заблоковано (бан) з наступних причин:";$locale['global_407'] = "Цей обліковий запис призупинено до ";$locale['global_408'] = " з наступних причин:";$locale['global_409'] = "Цей обліковий запис заблоковано (бан) з міркувань безпеки.";$locale['global_410'] = "Причина: ";$locale['global_411'] = "Цей обліковий запис скасовано.";$locale['global_412'] = "Цей обліковий запис зроблено анонімним, можливо, через бездіяльність.";
// Banning due to flooding$locale['global_440'] = "Автоматичний бан через порушення контролю за флудом";$locale['global_441'] = "Ваш обліковий запис заблоковано";$locale['global_442'] = "Вітаємо, [USER_NAME],\nЗ вашого облікового запису на сайті <<".$settings['sitename'].">> зафіксовано надсилання надто великої кількості повідомлень за короткий проміжок часу через адресу IP ".USER_IP.", що призвело до його блокування. Це було зроблено з метою попередження поширення спаму через бот-системи.\nБудь-ласка, зв'яжіться із адмінстрацією сайту через адресу E-mail ".$settings['siteemail']." , щоб розблокувати свій обліковий запис або повідомити про свою непричетність до зафіксованих потенційно шкідливих дій.\n".$settings['siteusername'];
// Lifting of suspension$locale['global_450'] = "Призупинення автоматично знято системою";$locale['global_451'] = "Знято призупинення облікового запису";$locale['global_452'] = "Вітаємо, USER_NAME,\nПризупинення дії Вашого облікового запису ".$settings['siteurl']." знято. Нагадуємо Ваші параметри авторизації на сайті:\nІм`я: USER_NAMEПароль: не показано з міркувань безпеки\nЯкщо Ви забули свій пароль, можете надіслати запит на новий через наступне посилання: LOST_PASSWORD\n\nЗ повагою,\n".$settings['siteusername'];$locale['global_453'] = "Вітаємо, USER_NAME,\nПризупинення дії Вашого облікового запису на ".$settings['siteurl']." знято.\n\nЗ повагою,\n".$settings['siteusername'];$locale['global_454'] = "Відновлено обліковий запис";$locale['global_455'] = "Вітаємо, USER_NAME,\nПід час Вашого останнього візиту на ".$settings['siteurl']." Ваш обліковий запис було відновлено і з нього знято статус неактивного.\n\nЗ повагою,\n".$settings['siteusername'];
// Function parsebytesize()$locale['global_460'] = " - ";$locale['global_461'] = " Байт";$locale['global_462'] = " Кб";$locale['global_463'] = " Мб";$locale['global_464'] = " Гб";$locale['global_465'] = " Тб";
//Safe Redirect$locale['global_500'] = "Ваш запит перенаправлено на %s, будь-ласка, зачекайте. Якщо перенаправлення не відбулось, натисніть тут";
// Captcha Locales$locale['global_600'] = "Код підтвердження";$locale['recaptcha'] = "en";
//Miscellaneous$locale['global_900'] = "Неможливо конвертувати HEX в DEC";//Language Selection$locale['global_ML100'] = "Мова:";$locale['global_ML101'] = "- виберіть мову -";$locale['global_ML102'] = "Мова сайту";$locale['flood'] = "Нові публікації заблоковані до завершення встановленого часу контролю за флудом. Будь ласка, зачекайте %t";$locale['no_image'] = "Зображення відсутнє";
?>